export const OVERUSED_ADVERBS: readonly string[] = [
  "đột nhiên",
  "bỗng nhiên",
  "tất nhiên",
  "rõ ràng",
  "thực ra",
  "thực sự",
  "hoàn toàn",
  "vô cùng",
  "cực kỳ",
  "thậm chí",
  "chắc chắn",
  "dường như",
  "hình như",
  "có vẻ như",
];

export const AI_TELL_PHRASES: readonly string[] = [
  "không thể phủ nhận",
  "không thể tránh khỏi",
  "điều này cho thấy",
  "đây là lúc",
  "trước khi kịp",
  "nhưng đó là lúc",
  "bỗng dưng nhận ra",
  "chợt nhận ra",
  "đột nhiên hiểu ra",
  "tim đập mạnh hơn",
  "trái tim thắt lại",
  "hơi thở trở nên gấp",
  "máu dồn lên mặt",
  "cảm thấy một làn sóng",
  "một luồng khí lạnh",
  "toát mồ hôi lạnh",
  "không biết phải làm gì",
  "không nói nên lời",
  "không biết phải nói gì",
];

export const CLICHE_PHRASES: readonly string[] = [
  "ánh mắt như dao",
  "nụ cười lạnh",
  "nụ cười khinh thường",
  "giọng nói lạnh như băng",
  "lạnh lùng như băng",
  "sắc bén như kiếm",
  "mạnh mẽ như núi",
  "nhanh như chớp",
  "im lặng đến ngộp thở",
  "im lặng bao trùm",
  "không khí đột ngột trở nên",
  "áp lực đè nặng",
  "khí thế hùng tráng",
  "hào quang tỏa ra",
  "khí tức ép xuống",
  "toàn trường im lặng",
  "không một ai dám",
  "chưa ai dám",
];

export const ALL_FATIGUE_TERMS: readonly string[] = [
  ...OVERUSED_ADVERBS,
  ...AI_TELL_PHRASES,
  ...CLICHE_PHRASES,
];
